### ISSUE TITLE
IllegalPluginAccessException on load

### ISSUE THREAD

**Issue by KevinDaGame** [jwdeveloper/SpigotTester#1]
Whenever SpigotTester tries to load a plugin before spigot does, calling methods on the plugin to test will result in exceptions.
This is especially relevant when a plugin registers events or commands to bukkit, and if loading is set to the default, POSTWORLD.

Tested software: 

- Papermc 1.19.3 build 399
- My own plugin, loading POSTWORLD
- SpigotTester v0.2.13-Release

Possible resolutions:
 - Set load to POSTWORLD
 - somehow add all plugins to loadbefore in plugin.yml
 - In onEnable catch a plugin that is not yet enabled, and don't run tests/schedule for later (max retries?)

Error: 
```
[19:34:04 WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register class org.bukkit.event.player.PlayerJoinEvent while not enabled
[19:34:04 WARN]: 	at org.bukkit.plugin.SimplePluginManager.registerEvent(SimplePluginManager.java:735)
[19:34:04 WARN]: 	at voxelsniper-8.4.3-spigot.jar//com.github.kevindagame.voxelsniper.libs.net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.registerEvent(BukkitAudiencesImpl.java:230)
[19:34:04 WARN]: 	at voxelsniper-8.4.3-spigot.jar//com.github.kevindagame.voxelsniper.libs.net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.<init>(BukkitAudiencesImpl.java:105)
[19:34:04 WARN]: 	at voxelsniper-8.4.3-spigot.jar//com.github.kevindagame.voxelsniper.libs.net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl$Builder.lambda$build$1(BukkitAudiencesImpl.java:175)
[19:34:04 WARN]: 	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
[19:34:04 WARN]: 	at java.base/java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2760)
[19:34:04 WARN]: 	at voxelsniper-8.4.3-spigot.jar//com.github.kevindagame.voxelsniper.libs.net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl$Builder.build(BukkitAudiencesImpl.java:173)
[19:34:04 WARN]: 	at voxelsniper-8.4.3-spigot.jar//com.github.kevindagame.voxelsniper.libs.net.kyori.adventure.platform.bukkit.BukkitAudiencesImpl.instanceFor(BukkitAudiencesImpl.java:89)
[19:34:04 WARN]: 	at voxelsniper-8.4.3-spigot.jar//com.github.kevindagame.voxelsniper.libs.net.kyori.adventure.platform.bukkit.BukkitAudiences.create(BukkitAudiences.java:53)
[19:34:04 WARN]: 	at voxelsniper-8.4.3-spigot.jar//com.github.kevindagame.voxelsniper.SpigotVoxelSniper.onEnable(SpigotVoxelSniper.java:79)
[19:34:04 WARN]: 	at SpigotTester.jar//io.github.jwdeveloper.spigot.tester.plugin.PluginMain.runTests(PluginMain.java:79)
[19:34:04 WARN]: 	at SpigotTester.jar//io.github.jwdeveloper.spigot.tester.plugin.PluginMain.onEnable(PluginMain.java:59)
[19:34:04 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[19:34:04 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371)
[19:34:04 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544)
[19:34:04 WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:578)
[19:34:04 WARN]: 	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:492)
[19:34:04 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:274)
[19:34:04 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1101)
[19:34:04 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[19:34:04 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by jwdeveloper** [comment]
`somehow add all plugins to loadbefore in plugin.yml`. 

Issue has been resolved by scheduling task that checking if all other plugins has been enabled. Then tests are being run
More details in the release description

https://github.com/jwdeveloper/SpigotTester/releases/tag/1.0.0-Release
```
<dependency>
  <groupId>com.github.jwdeveloper</groupId>
  <artifactId>SpigotTester</artifactId>
  <version>1.0.0-Release</version>
</dependency>
```
